export const WORD_PAIRS: Record<string, Array<{ en: string, es: string }>> = {
  'Personality': [
    { en: 'Albert Einstein', es: 'Albert Einstein' },
    { en: 'Batman', es: 'Batman' },
    { en: 'Sherlock Holmes', es: 'Sherlock Holmes' },
    { en: 'Taylor Swift', es: 'Taylor Swift' },
    { en: 'Elon Musk', es: 'Elon Musk' },
    { en: 'Abraham Lincoln', es: 'Abraham Lincoln' },
    { en: 'Marilyn Monroe', es: 'Marilyn Monroe' },
    { en: 'Harry Potter', es: 'Harry Potter' },
    { en: 'Elvis Presley', es: 'Elvis Presley' },
    { en: 'Steve Jobs', es: 'Steve Jobs' },
    { en: 'William Shakespeare', es: 'William Shakespeare' },
    { en: 'Leonardo da Vinci', es: 'Leonardo da Vinci' },
    { en: 'Marie Curie', es: 'Marie Curie' },
    { en: 'Michael Jordan', es: 'Michael Jordan' },
    { en: 'Beyoncé', es: 'Beyoncé' },
    { en: 'Spider-Man', es: 'Spider-Man' },
    { en: 'Wonder Woman', es: 'Wonder Woman' },
    { en: 'Joker', es: 'Joker' },
    { en: 'Darth Vader', es: 'Darth Vader' },
    { en: 'Iron Man', es: 'Iron Man' },
    { en: 'Cleopatra', es: 'Cleopatra' },
    { en: 'Winston Churchill', es: 'Winston Churchill' },
    { en: 'Nelson Mandela', es: 'Nelson Mandela' },
    { en: 'Ghandi', es: 'Ghandi' },
    { en: 'Mother Teresa', es: 'Teresa de Calcuta' },
    { en: 'Isaac Newton', es: 'Isaac Newton' },
    { en: 'Charles Darwin', es: 'Charles Darwin' },
    { en: 'Stephen Hawking', es: 'Stephen Hawking' },
    { en: 'Bill Gates', es: 'Bill Gates' },
    { en: 'Mark Zuckerberg', es: 'Mark Zuckerberg' },
    { en: 'Oprah Winfrey', es: 'Oprah Winfrey' },
    { en: 'Muhammad Ali', es: 'Muhammad Ali' },
    { en: 'Serena Williams', es: 'Serena Williams' },
    { en: 'Tiger Woods', es: 'Tiger Woods' },
    { en: 'Cristiano Ronaldo', es: 'Cristiano Ronaldo' },
    { en: 'Lionel Messi', es: 'Lionel Messi' },
    { en: 'Lady Gaga', es: 'Lady Gaga' },
    { en: 'Freddie Mercury', es: 'Freddie Mercury' },
    { en: 'Michael Jackson', es: 'Michael Jackson' },
    { en: 'David Bowie', es: 'David Bowie' },
    { en: 'John Lennon', es: 'John Lennon' },
    { en: 'Walt Disney', es: 'Walt Disney' },
    { en: 'Charlie Chaplin', es: 'Charlie Chaplin' },
    { en: 'Audrey Hepburn', es: 'Audrey Hepburn' },
    { en: 'Tom Hanks', es: 'Tom Hanks' },
    { en: 'Meryl Streep', es: 'Meryl Streep' },
    { en: 'Brad Pitt', es: 'Brad Pitt' },
    { en: 'Angelina Jolie', es: 'Angelina Jolie' },
    { en: 'Johnny Depp', es: 'Johnny Depp' },
    { en: 'Will Smith', es: 'Will Smith' },
    { en: 'Leonardo DiCaprio', es: 'Leonardo DiCaprio' },
    { en: 'Luke Skywalker', es: 'Luke Skywalker' },
    { en: 'Frodo Baggins', es: 'Frodo Bolsón' },
    { en: 'James Bond', es: 'James Bond' },
    { en: 'Indiana Jones', es: 'Indiana Jones' },
    { en: 'Katniss Everdeen', es: 'Katniss Everdeen' },
    { en: 'Hermione Granger', es: 'Hermione Granger' },
    { en: 'Black Widow', es: 'Viuda Negra' },
    { en: 'Captain America', es: 'Capitán América' },
    { en: 'Thor', es: 'Thor' },
    { en: 'Hulk', es: 'Hulk' },
    { en: 'Superman', es: 'Superman' }
  ],
  'Object': [
    { en: 'Toaster', es: 'Tostadora' },
    { en: 'Spaceship', es: 'Nave espacial' },
    { en: 'Umbrella', es: 'Paraguas' },
    { en: 'Microscope', es: 'Microscopio' },
    { en: 'Compass', es: 'Brújula' },
    { en: 'Telescope', es: 'Telescopio' },
    { en: 'Typewriter', es: 'Máquina de escribir' },
    { en: 'Backpack', es: 'Mochila' },
    { en: 'Headphones', es: 'Auriculares' },
    { en: 'Sunglasses', es: 'Gafas de sol' },
    { en: 'Hammer', es: 'Martillo' },
    { en: 'Flashlight', es: 'Linterna' },
    { en: 'Key', es: 'Llave' },
    { en: 'Wallet', es: 'Billetera' },
    { en: 'Mirror', es: 'Espejo' },
    { en: 'Clock', es: 'Reloj' },
    { en: 'Guitar', es: 'Guitarra' },
    { en: 'Camera', es: 'Cámara' },
    { en: 'Bicycle', es: 'Bicicleta' },
    { en: 'Laptop', es: 'Portátil' },
    { en: 'Microphone', es: 'Micrófono' },
    { en: 'Piano', es: 'Piano' },
    { en: 'Violin', es: 'Violín' },
    { en: 'Drum Set', es: 'Batería' },
    { en: 'Saxophone', es: 'Saxofón' },
    { en: 'Trumpet', es: 'Trompeta' },
    { en: 'Flute', es: 'Flauta' },
    { en: 'Skateboard', es: 'Monopatín' },
    { en: 'Surfboard', es: 'Tabla de surf' },
    { en: 'Snowboard', es: 'Snowboard' },
    { en: 'Rollerblades', es: 'Patines' },
    { en: 'Scooter', es: 'Patinete' },
    { en: 'Motorcycle', es: 'Motocicleta' },
    { en: 'Helicopter', es: 'Helicóptero' },
    { en: 'Submarine', es: 'Submarino' },
    { en: 'Hot Air Balloon', es: 'Globo aerostático' },
    { en: 'Parachute', es: 'Paracaídas' },
    { en: 'Drone', es: 'Dron' },
    { en: 'Robot', es: 'Robot' },
    { en: 'Smartphone', es: 'Smartphone' },
    { en: 'Tablet', es: 'Tablet' },
    { en: 'Television', es: 'Televisión' },
    { en: 'Projector', es: 'Proyector' },
    { en: 'Printer', es: 'Impresora' },
    { en: 'Scanner', es: 'Escáner' },
    { en: 'Washing Machine', es: 'Lavadora' },
    { en: 'Dishwasher', es: 'Lavavajillas' },
    { en: 'Refrigerator', es: 'Nevera' },
    { en: 'Microwave', es: 'Microondas' },
    { en: 'Coffee Maker', es: 'Cafetera' },
    { en: 'Blender', es: 'Batidora' },
    { en: 'Juicer', es: 'Exprimidor' },
    { en: 'Vacuum Cleaner', es: 'Aspiradora' },
    { en: 'Iron', es: 'Plancha' },
    { en: 'Hair Dryer', es: 'Secador de pelo' },
    { en: 'Electric Toothbrush', es: 'Cepillo de dientes eléctrico' },
    { en: 'Stethoscope', es: 'Estetoscopio' },
    { en: 'Thermometer', es: 'Termómetro' },
    { en: 'Calculator', es: 'Calculadora' },
    { en: 'Abacus', es: 'Ábaco' },
    { en: 'Globe', es: 'Globo terráqueo' },
    { en: 'Map', es: 'Mapa' }
  ],
  'Idea': [
    { en: 'Democracy', es: 'Democracia' },
    { en: 'Evolution', es: 'Evolución' },
    { en: 'Gravity', es: 'Gravedad' },
    { en: 'Internet', es: 'Internet' },
    { en: 'Time Travel', es: 'Viaje en el tiempo' },
    { en: 'Freedom', es: 'Libertad' },
    { en: 'Justice', es: 'Justicia' },
    { en: 'Love', es: 'Amor' },
    { en: 'Infinity', es: 'Infinito' },
    { en: 'Artificial Intelligence', es: 'Inteligencia Artificial' },
    { en: 'Global Warming', es: 'Calentamiento Global' },
    { en: 'Capitalism', es: 'Capitalismo' },
    { en: 'Socialism', es: 'Socialismo' },
    { en: 'Philosophy', es: 'Filosofía' },
    { en: 'Quantum Physics', es: 'Física Cuántica' },
    { en: 'Dreams', es: 'Sueños' },
    { en: 'Memory', es: 'Memoria' },
    { en: 'Happiness', es: 'Felicidad' },
    { en: 'Courage', es: 'Coraje' },
    { en: 'Honesty', es: 'Honestidad' },
    { en: 'Loyalty', es: 'Lealtad' },
    { en: 'Wisdom', es: 'Sabiduría' },
    { en: 'Knowledge', es: 'Conocimiento' },
    { en: 'Truth', es: 'Verdad' },
    { en: 'Beauty', es: 'Belleza' },
    { en: 'Art', es: 'Arte' },
    { en: 'Music', es: 'Música' },
    { en: 'Science', es: 'Ciencia' },
    { en: 'Mathematics', es: 'Matemáticas' },
    { en: 'History', es: 'Historia' },
    { en: 'Geography', es: 'Geografía' },
    { en: 'Religion', es: 'Religión' },
    { en: 'Spirituality', es: 'Espiritualidad' },
    { en: 'Meditation', es: 'Meditación' },
    { en: 'Yoga', es: 'Yoga' },
    { en: 'Mindfulness', es: 'Atención plena' },
    { en: 'Psychology', es: 'Psicología' },
    { en: 'Sociology', es: 'Sociología' },
    { en: 'Economics', es: 'Economía' },
    { en: 'Politics', es: 'Política' },
    { en: 'Law', es: 'Ley' },
    { en: 'Ethics', es: 'Ética' },
    { en: 'Morality', es: 'Moralidad' },
    { en: 'Culture', es: 'Cultura' },
    { en: 'Tradition', es: 'Tradición' },
    { en: 'Innovation', es: 'Innovación' },
    { en: 'Creativity', es: 'Creatividad' },
    { en: 'Imagination', es: 'Imaginación' },
    { en: 'Inspiration', es: 'Inspiración' },
    { en: 'Success', es: 'Éxito' },
    { en: 'Failure', es: 'Fracaso' },
    { en: 'Victory', es: 'Victoria' },
    { en: 'Defeat', es: 'Derrota' },
    { en: 'Peace', es: 'Paz' },
    { en: 'War', es: 'Guerra' },
    { en: 'Conflict', es: 'Conflicto' },
    { en: 'Resolution', es: 'Resolución' },
    { en: 'Communication', es: 'Comunicación' },
    { en: 'Language', es: 'Lenguaje' },
    { en: 'Literature', es: 'Literatura' },
    { en: 'Poetry', es: 'Poesía' },
    { en: 'Drama', es: 'Drama' },
    { en: 'Comedy', es: 'Comedia' },
    { en: 'Tragedy', es: 'Tragedia' }
  ],
  'Place': [
    { en: 'Paris', es: 'París' },
    { en: 'The Moon', es: 'La Luna' },
    { en: 'Amazon Rainforest', es: 'Selva Amazónica' },
    { en: 'Grand Canyon', es: 'Gran Cañón' },
    { en: 'Great Wall of China', es: 'Gran Muralla China' },
    { en: 'New York City', es: 'Nueva York' },
    { en: 'Tokyo', es: 'Tokio' },
    { en: 'Egypt Pyramids', es: 'Pirámides de Egipto' },
    { en: 'Antarctica', es: 'Antártida' },
    { en: 'Mount Everest', es: 'Monte Everest' },
    { en: 'Rome', es: 'Roma' },
    { en: 'London', es: 'Londres' },
    { en: 'Sydney Opera House', es: 'Ópera de Sídney' },
    { en: 'Sahara Desert', es: 'Desierto del Sahara' },
    { en: 'Hollywood', es: 'Hollywood' },
    { en: 'Venice', es: 'Venecia' },
    { en: 'Rio de Janeiro', es: 'Río de Janeiro' },
    { en: 'Machu Picchu', es: 'Machu Picchu' },
    { en: 'Taj Mahal', es: 'Taj Mahal' },
    { en: 'Eiffel Tower', es: 'Torre Eiffel' },
    { en: 'Statue of Liberty', es: 'Estatua de la Libertad' },
    { en: 'Big Ben', es: 'Big Ben' },
    { en: 'Colosseum', es: 'Coliseo' },
    { en: 'Acropolis', es: 'Acrópolis' },
    { en: 'Petra', es: 'Petra' },
    { en: 'Angkor Wat', es: 'Angkor Wat' },
    { en: 'Galapagos Islands', es: 'Islas Galápagos' },
    { en: 'Great Barrier Reef', es: 'Gran Barrera de Coral' },
    { en: 'Niagara Falls', es: 'Cataratas del Niágara' },
    { en: 'Victoria Falls', es: 'Cataratas Victoria' },
    { en: 'Mount Fuji', es: 'Monte Fuji' },
    { en: 'Kilimanjaro', es: 'Kilimanjaro' },
    { en: 'The Alps', es: 'Los Alpes' },
    { en: 'The Himalayas', es: 'El Himalaya' },
    { en: 'The Andes', es: 'Los Andes' },
    { en: 'Gobi Desert', es: 'Desierto de Gobi' },
    { en: 'Death Valley', es: 'Valle de la Muerte' },
    { en: 'Bermuda Triangle', es: 'Triángulo de las Bermudas' },
    { en: 'Atlantis', es: 'Atlántida' },
    { en: 'Mars', es: 'Marte' },
    { en: 'Jupiter', es: 'Júpiter' },
    { en: 'Saturn', es: 'Saturno' },
    { en: 'Black Hole', es: 'Agujero Negro' },
    { en: 'Milky Way', es: 'Vía Láctea' },
    { en: 'Andromeda Galaxy', es: 'Galaxia de Andrómeda' },
    { en: 'North Pole', es: 'Polo Norte' },
    { en: 'South Pole', es: 'Polo Sur' },
    { en: 'Equator', es: 'Ecuador' },
    { en: 'Easter Island', es: 'Isla de Pascua' },
    { en: 'Stonehenge', es: 'Stonehenge' },
    { en: 'Santorini', es: 'Santorini' }
  ],
  'Movie': [
    { en: 'Inception', es: 'Origen' },
    { en: 'The Lion King', es: 'El Rey León' },
    { en: 'Star Wars', es: 'La Guerra de las Galaxias' },
    { en: 'Titanic', es: 'Titanic' },
    { en: 'The Matrix', es: 'Matrix' },
    { en: 'Jurassic Park', es: 'Parque Jurásico' },
    { en: 'Toy Story', es: 'Toy Story' },
    { en: 'The Godfather', es: 'El Padrino' },
    { en: 'Avatar', es: 'Avatar' },
    { en: 'Harry Potter', es: 'Harry Potter' },
    { en: 'The Avengers', es: 'Los Vengadores' },
    { en: 'Frozen', es: 'Frozen' },
    { en: 'Pulp Fiction', es: 'Pulp Fiction' },
    { en: 'The Dark Knight', es: 'El Caballero Oscuro' },
    { en: 'Interstellar', es: 'Interstellar' },
    { en: 'Shrek', es: 'Shrek' },
    { en: 'Finding Nemo', es: 'Buscando a Nemo' },
    { en: 'Back to the Future', es: 'Regreso al Futuro' },
    { en: 'Ghostbusters', es: 'Cazafantasmas' },
    { en: 'Indiana Jones', es: 'Indiana Jones' },
    { en: 'The Lord of the Rings', es: 'El Señor de los Anillos' },
    { en: 'The Hobbit', es: 'El Hobbit' },
    { en: 'Gladiator', es: 'Gladiator' },
    { en: 'Braveheart', es: 'Braveheart' },
    { en: 'Saving Private Ryan', es: 'Salvar al Soldado Ryan' },
    { en: 'Schindler\'s List', es: 'La Lista de Schindler' },
    { en: 'Forrest Gump', es: 'Forrest Gump' },
    { en: 'The Shawshank Redemption', es: 'Cadena Perpetua' },
    { en: 'The Green Mile', es: 'La Milla Verde' },
    { en: 'Fight Club', es: 'El Club de la Lucha' },
    { en: 'The Silence of the Lambs', es: 'El Silencio de los Corderos' },
    { en: 'Se7en', es: 'Seven' },
    { en: 'The Usual Suspects', es: 'Sospechosos Habituales' },
    { en: 'The Prestige', es: 'El Truco Final' },
    { en: 'Memento', es: 'Memento' },
    { en: 'The Departed', es: 'Infiltrados' },
    { en: 'Goodfellas', es: 'Uno de los Nuestros' },
    { en: 'Casino', es: 'Casino' },
    { en: 'Scarface', es: 'Scarface' },
    { en: 'The Terminator', es: 'Terminator' },
    { en: 'Alien', es: 'Alien' },
    { en: 'Predator', es: 'Predator' },
    { en: 'Blade Runner', es: 'Blade Runner' },
    { en: 'The Shining', es: 'El Resplandor' },
    { en: 'Psycho', es: 'Psicosis' },
    { en: 'Jaws', es: 'Tiburón' },
    { en: 'Rocky', es: 'Rocky' },
    { en: 'Die Hard', es: 'Jungla de Cristal' },
    { en: 'Mad Max', es: 'Mad Max' },
    { en: 'The Big Lebowski', es: 'El Gran Lebowski' },
    { en: 'Groundhog Day', es: 'Atrapado en el Tiempo' },
    { en: 'The Truman Show', es: 'El Show de Truman' }
  ],
  'Animal': [
    { en: 'Elephant', es: 'Elefante' },
    { en: 'Penguin', es: 'Pingüino' },
    { en: 'Giraffe', es: 'Jirafa' },
    { en: 'Octopus', es: 'Pulpo' },
    { en: 'Kangaroo', es: 'Canguro' },
    { en: 'Lion', es: 'León' },
    { en: 'Tiger', es: 'Tigre' },
    { en: 'Shark', es: 'Tiburón' },
    { en: 'Eagle', es: 'Águila' },
    { en: 'Wolf', es: 'Lobo' },
    { en: 'Dolphin', es: 'Delfín' },
    { en: 'Panda', es: 'Panda' },
    { en: 'Koala', es: 'Koala' },
    { en: 'Zebra', es: 'Cebra' },
    { en: 'Cheetah', es: 'Guepardo' },
    { en: 'Owl', es: 'Búho' },
    { en: 'Butterfly', es: 'Mariposa' },
    { en: 'Crocodile', es: 'Cocodrilo' },
    { en: 'Gorilla', es: 'Gorila' },
    { en: 'Honey Bee', es: 'Abeja' },
    { en: 'Whale', es: 'Ballena' },
    { en: 'Polar Bear', es: 'Oso Polar' },
    { en: 'Hippopotamus', es: 'Hipopótamo' },
    { en: 'Rhinoceros', es: 'Rinoceronte' },
    { en: 'Chimpanzee', es: 'Chimpancé' },
    { en: 'Orangutan', es: 'Orangután' },
    { en: 'Lemur', es: 'Lémur' },
    { en: 'Sloth', es: 'Perezoso' },
    { en: 'Platypus', es: 'Ornitorrinco' },
    { en: 'Echidna', es: 'Equidna' },
    { en: 'Ostrich', es: 'Avestruz' },
    { en: 'Flamingo', es: 'Flamenco' },
    { en: 'Peacock', es: 'Pavo Real' },
    { en: 'Parrot', es: 'Loro' },
    { en: 'Toucan', es: 'Tucán' },
    { en: 'Hummingbird', es: 'Colibrí' },
    { en: 'Sea Turtle', es: 'Tortuga Marina' },
    { en: 'Seahorse', es: 'Caballito de Mar' },
    { en: 'Starfish', es: 'Estrella de Mar' },
    { en: 'Jellyfish', es: 'Medusa' },
    { en: 'Coral', es: 'Coral' },
    { en: 'Camel', es: 'Camello' },
    { en: 'Llama', es: 'Llama' },
    { en: 'Alpaca', es: 'Alpaca' },
    { en: 'Yak', es: 'Yak' },
    { en: 'Arctic Fox', es: 'Zorro Ártico' },
    { en: 'Snow Leopard', es: 'Leopardo de las Nieves' },
    { en: 'Red Panda', es: 'Panda Rojo' },
    { en: 'Axolotl', es: 'Ajolote' },
    { en: 'Narwhal', es: 'Narval' },
    { en: 'Walrus', es: 'Morsa' },
    { en: 'Seal', es: 'Foca' },
    { en: 'Otter', es: 'Nutria' },
    { en: 'Beaver', es: 'Castor' },
    { en: 'Badger', es: 'Tejón' },
    { en: 'Hedgehog', es: 'Erizo' }
  ]
};
